services:
  db:
    image: postgres:14.3-alpine
    ports:
      - "9753:5432"
    env_file:
      - .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: test_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - test

  backend:
    build: .
    ports:
      - "8000:8000"
    container_name: test_backend
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    volumes:
      - .:/code
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    networks:
      - test

volumes:
  postgres_data:

networks:
  test:
    name: test