name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Add environ
      run: cp .env.test .env

    - name: Run Tests
      run: |
        docker-compose run -T --rm backend bash -c "coverage run --source='.'  /code/manage.py test && coverage report"

    - name: Debug Info
      run: |
        echo "DATABASE_URL: $DATABASE_URL"
        echo "Trying to connect to the database..."
        psql -h db -U test -d test -c "SELECT 1;"
